openapi: 3.0.0
info:
  title: Rex
  description: Rex is a tool for keeping track of ideas for things to do and
    providing, on demand, a random one.
  license:
    name: MIT
    url: https://sierrasoftworks.com/licenses/MIT
  version: 3.0.

servers:
  - url: https://rex.sierrasoftworks.com
  - url: http://localhost:8000

tags:
  - name: health
    description: APIs used to determine the health of a Rex instance.
  - name: ideas
    description: APIs used to manage and retrieve ideas.
  - name: collections
    description: APIs used to manage collections of ideas.
  - name: diagnostics
    description: APIs used to triage and diagnose problems with the service.
paths:
  /api/v1/auth:
    get:
      tags:
        - diagnostics

      summary: Get Authentication Claims (v1)
      description: Gets the claims that the submitted authorization token offers.
      operationId: auth_info_v1
  /api/v1/health:
    get:
      tags:
        - health

      summary: Get Health (v1)
      description: Gets the current health status of the Rex instance.
      operationId: health_v1
      deprecated: true
  /api/v2/health:
    get:
      tags:
        - health

      summary: Get Health (v2)
      description: Gets the current health status of the Rex instance.
      operationId: health_v2
  /api/v1/ideas:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Ideas (v1)
      description: Gets the list of ideas registered with the server.
      operationId: ideas_v1
      deprecated: true

    post:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: New Idea (v1)
      description: Creates a new idea on the server.
      operationId: new_idea_v1
      deprecated: true
  /api/v1/idea/random:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Random Idea (v1)
      description: Gets a single randomly selected idea from the server.
      operationId: random_idea_v1
      deprecated: true
  /api/v1/idea/{id}:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Idea (v1)
      description: Gets a specific idea from the server based on its ID.
      operationId: idea_v1
      deprecated: true
    put:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Store Idea (v1)
      description: Stores an idea idempotently with the given identifier, replacing an existing instance if one is present.
      operationId: store_idea_v1
      deprecated: true
    delete:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Remove Idea (v1)
      description: Removes a specific idea from the server based on its ID.
      operationId: remove_idea_v1
      deprecated: true
  /api/v2/ideas:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Ideas (v2)
      description: Gets the list of ideas registered with the server.
      operationId: ideas_v2
    post:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: New Idea (v2)
      description: Creates a new idea on the server.
      operationId: new_idea_v2
  /api/v2/idea/random:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Random Idea (v2)
      description: Gets a single randomly selected idea from the server.
      operationId: random_idea_v2
  /api/v2/idea/{id}:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Idea (v2)
      description: Gets a specific idea from the server based on its ID.
      operationId: idea_v2
    put:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Store Idea (v2)
      description: Stores an idea idempotently with the given identifier, replacing an existing instance if one is present.
      operationId: store_idea_v2
    delete:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Remove Idea (v2)
      description: Removes a specific idea from the server based on its ID.
      operationId: remove_idea_v2
  /api/v3/ideas:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Ideas (v3)
      description: Gets the list of ideas registered with the server.
      operationId: ideas_v3
    post:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: New Idea (v3)
      description: Creates a new idea on the server.
      operationId: new_idea_v3
  /api/v3/idea/random:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Random Idea (v3)
      description: Gets a single randomly selected idea from the server.
      operationId: random_idea_v3
  /api/v3/idea/{id}:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Idea (v3)
      description: Gets a specific idea from the server based on its ID.
      operationId: idea_v3
    put:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Store Idea (v2)
      description: Stores an idea idempotently with the given identifier, replacing an existing instance if one is present.
      operationId: store_idea_v3
    delete:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Remove Idea (v3)
      description: Removes a specific idea from the server based on its ID.
      operationId: remove_idea_v3
  /api/v3/collection/{collectionId}/ideas:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Ideas (v3)
      description: Gets the list of ideas registered with the server.
      operationId: ideas_by_collection_v3
    post:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: New Idea (v3)
      description: Creates a new idea on the server.
      operationId: new_idea_by_collection_v3
  /api/v3/collection/{collectionId}/idea/random:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Random Idea (v3)
      description: Gets a single randomly selected idea from the server.
      operationId: random_idea_by_collection_v3
  /api/v3/collection/{collectionId}/idea/{id}:
    get:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Read]

      summary: Get Idea (v3)
      description: Gets a specific idea from the server based on its ID.
      operationId: idea_by_collection_v3
    put:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Store Idea (v3)
      description: Stores an idea idempotently with the given identifier, replacing an existing instance if one is present.
      operationId: store_idea_by_collection_v3
    delete:
      tags:
        - ideas
      security:
        - AzureAD: [Ideas.Write]

      summary: Remove Idea (v3)
      description: Removes a specific idea from the server based on its ID.
      operationId: remove_idea_by_collection_v3
  /api/v3/collections:
    get:
      tags:
        - collections
      security:
        - AzureAD: [Collections.Read]

      summary: Get Collections (v3)
      description: Gets the list of collections that this user can access.
      operationId: collections_v3
    post:
      tags:
        - collections
      security:
        - AzureAD: [Collections.Write]

      summary: New Collection (v3)
      description: Creates a new collection with the provided name.
      operationId: new_collection_v3
  /api/v3/collection/{collectionId}:
    get:
      tags:
        - collections
      security:
        - AzureAD: [Collections.Read]

      summary: Get Collection (v3)
      description: Gets a collection that a user can access by its ID.
      operationId: collection_v3
    delete:
      tags:
        - collections
      security:
        - AzureAD: [Collections.Write]

      summary: Remove Collection (v3)
      description: Removes a collection from a user's list using its ID.
      operationId: remove_collection_v3
  /api/v3/collection/{collectionId}/users:
    get:
      tags:
        - collections
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Get Collection Role Assignments (v3)
      description: Gets the list of users which can access this collection and their role assignments.
      operationId: role_assignments_v3
  /api/v3/collection/{collectionId}/user/{userId}:
    get:
      tags:
        - collections
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Get User Role Assignment (v3)
      description: Gets the details of a user's role assignment within a collection.
      operationId: role_assignment_v3
    put:
      tags:
        - collections
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Update User Role Assignment (v3)
      description: Update the role assignment associated with a user on a given collection.
      operationId: update_role_assignment_v3
    delete:
      tags:
        - collections
      security:
        - AzureAD: [RoleAssignments.Write]

      summary: Remove User Role Assignment (v3)
      description: Removes a user's role assignment from a collection.
      operationId: remove_role_assignment_v3
components:
  securitySchemes:
    AzureAD:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://login.microsoftonline.com/a26571f1-22b3-4756-ac7b-39ca684fab48/oauth2/v2.0/authorize
          scopes:
            "Ideas.Read": Allows the reading of ideas.
            "Ideas.Write": Allows the creation, modification and deletion of ideas.
            "Collections.Read": Allows the reading of collection information.
            "Collections.Write": Allows the creation, modification and removal of collections.
            "RoleAssignments.Write": Allows the creation, modification and removal of role assignments for collections.
